name : UQ Computing Society Tips
brand : UQ Computing Society
description : Tips brought to you by the UQ Computing Society
keyword :
url : http://UQComputingSociety.github.io/tips/
email : contact@uqcs.org.au
twitter : UQComputing
github : UQComputingSociety
author : UQ Computing Society
analytics : UA-59689206-1
year : 2015
markdown : kramdown
exclude :
  - node_modules
